stages:
  get_data:
    cmd: python src/data/clean_data.py data/interim/data_regional.csv data/interim/data_cleaned.csv
    deps:
      - data/interim/data_regional.csv
      - src/data/clean_data.py
    outs:
      - data/interim/data_cleaned.csv

  add_features:
    cmd: python src/features/add_features.py data/interim/data_cleaned.csv data/interim/data_featured.csv
    deps:
      - data/interim/data_cleaned.csv
      - src/features/add_features.py
    outs:
      - data/interim/data_featured.csv

  add_cafes_in_radius:
    cmd: python src/features/add_cafe_radius_features.py data/interim/data_featured.csv data/external/data_cafes.geojson data/processed/dataset.csv
    deps:
      - data/interim/data_featured.csv
      - data/external/data_cafes.geojson
      - src/features/add_cafe_radius_features.py
    outs:
      - data/processed/dataset.csv

  prepare_datasets:
    cmd: python src/models/prepare_datasets.py data/processed/dataset.csv data/processed/train.csv data/processed/test.csv
    deps:
      - data/processed/dataset.csv
      - src/models/prepare_datasets.py
    outs:
      - data/processed/train.csv
      - data/processed/test.csv

  train:
    cmd: python src/models/train.py data/processed/train.csv data/processed/test.csv models/model.clf reports/metrics.json
    deps:
      - data/processed/train.csv
      - data/processed/test.csv
      - src/models/train.py
    outs:
      - models/model.clf
      - reports/metrics.json